name: 'IPFS Web3.storage Cloudflare Action'
description: 'Add site to IPFS via web3.storage and set dnslink on Cloudflare'
inputs:
  path_to_add:  # id of input
    description: 'Path to add'
    required: true
    default: 'dist'
  web3_token:  # id of input
    description: 'web3.storage API token'
    required: true
  cloudflare-api-token:
    description: 'Cloudflare API token'
    required: true
  domain:
    description: 'Domain'
    required: true
  zone_id:
    description: 'Zone ID'
    required: true
runs:
  using: "composite"
  steps:
    - uses: web3-storage/add-to-web3@v2
      id: web3
      with:
        web3_token: ${{ inputs.web3_token }}
        path_to_add: ${{ inputs.path_to_add }}

    - run: python ${{ github.action_path }}/update-cloudflare-dns.py
      shell: bash
      env:
        CID: ${{ steps.web3.outputs.cid }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        ZONE_ID: ${{ inputs.zone_id }}
